I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 429, in script
    " "
  File "renpy/common/00action_other.rpy", line 517, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/map.rpy", line 36, in moveDenizen
    if self.isEmpty(x, y):
  File "game/map.rpy", line 25, in isEmpty
    return self.map[y][x].occupant is None
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 429, in script
    " "
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\ast.py", line 652, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\exports.py", line 1198, in say
    who(what, *args, **kwargs)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\character.py", line 1016, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\character.py", line 817, in do_display
    **display_args)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\character.py", line 566, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\display\core.py", line 2649, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\display\core.py", line 3451, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\display\layout.py", line 992, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\display\layout.py", line 992, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\display\layout.py", line 992, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\display\screen.py", line 697, in event
    rv = self.child.event(ev, x, y, st)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\display\layout.py", line 992, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\display\behavior.py", line 439, in event
    rv = run(action)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\display\behavior.py", line 308, in run
    new_rv = run(i, *args, **kwargs)
  File "E:\_RenPy\renpy-7.0.0-sdk\renpy\display\behavior.py", line 315, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_other.rpy", line 517, in __call__
    rv = self.callable(*self.args, **self.kwargs)
  File "game/map.rpy", line 36, in moveDenizen
    if self.isEmpty(x, y):
  File "game/map.rpy", line 25, in isEmpty
    return self.map[y][x].occupant is None
IndexError: list index out of range

Windows-8-6.2.9200
Ren'Py 7.0.0.108
Crimson Rue 1.0
Sun Oct 07 17:21:55 2018
