I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/common route.rpy", line 141, in script
    
  File "game/common route.rpy", line 141, in <module>
    
NameError: name 'falling' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/common route.rpy", line 141, in script
    
  File "E:\_RenPy\renpy-6.99.13-sdk\renpy\ast.py", line 1089, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "E:\_RenPy\renpy-6.99.13-sdk\renpy\ast.py", line 1050, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "E:\_RenPy\renpy-6.99.13-sdk\renpy\python.py", line 1794, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "E:\_RenPy\renpy-6.99.13-sdk\renpy\python.py", line 1788, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/common route.rpy", line 141, in <module>
    
NameError: name 'falling' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.13.2919
Crimson Rue 1.0
